```{r setup-general, include = FALSE}
library("tidyverse")
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup-box, include = FALSE}
# Using bulb and warning icon from ionicons
htmltools::tagList(rmarkdown::html_dependency_ionicons())

# Don't use knitr::opts_chunk$set() for box.collapse: we would like solution boxes
# to be collapsed by default but not warnings and advices...
knitr::opts_hooks$set(solution = function(options) {
  if (isTRUE(options$solution) && is.null(options$box.collapse)) {
    if (str_detect(knitr::current_input(), "^project")) options$box.collapse <- NULL
    else options$box.collapse <- TRUE
    }
  options
})

# Create a new chunk option: box.type
# We setup box colours, titles and add an icon for advices and warnings
# Should be somehow included in a future unilur release (define box types to be reused)
knitr::opts_hooks$set(box.type = function(options) {
    box_types <- list(
    advice = c(
      box_title = "Tip",
      box_colour = "#FFEC8B",
      box_icon = "ion-lightbulb"),
    warning = c(
      box_title = "Warning",
      box_colour = "#FFAD99",
      box_icon = "ion-android-alert")
  )
  
  if (options$box.type %in% names(box_types)) {
    options$box.colour = box_types[[options$box.type]]["box_colour"]
    
    if (is.null(options$box.title)) options$box.title <- box_types[[options$box.type]]['box_title']
    
    options$box.title <- glue::glue("<i class=\"icon {box_types[[options$box.type]][['box_icon']]}\"></i>\t{options$box.title}")
  }
  options
})
```

