---
title: "Geovisualization and Spatial Analysis"
author: "Kim Antunez & Timothée Giraud"
date: "Massive spatial data: challenges in acquisition, treatment and use for territories"
output:
  unilur::tutorial_html_solution:
    toc: true
    toc_float: false
    toc_depth: 1
    solution_suffix: ""
    theme: journal #journal ou cosmo
    css: css_file.css
    self_contained: no
    number_sections: no
---



```{r setup-practical, child = '_setup.Rmd'}
```

```{r knitr_init, echo=FALSE, cache=FALSE}
#remotes::install_github("koncina/unilur@dev")
library(knitr)
## Global options
options(max.print="90")
opts_chunk$set(echo=TRUE,
	             cache=FALSE, #TRUE
               prompt=FALSE,
               tidy=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=90)
options(width = 90)

# no margins
knit_hooks$set(nm = function(before, options, envir){
  if (before){
    par(mar=c(0,0,0,0))
  }
})

# title margins
knit_hooks$set(sm = function(before, options, envir){
  if (before){
    par(mar=c(0,0,1.2,0))
  }
})


```

# Exercice 1 : Faire des additions



Bloc solution avec du code

```{r, echo=F}
1+1
```
```{r, eval=F, solution = TRUE}
1+1
```


Bloc solution avec du texte
```{block, solution = TRUE}
Voici du texte
```

# Exercice 2 : Faire des multiplications

Bloc advice

```{block, box.title=" Clue",box.type = "advice"}
Si vous voulez faire une **carte**, utilisez cartography !
```


```{block,box.title="Bloc personnalisé",box.colour="#FF0099"}
Changer la couleur du block
```



##### {.bonus}
Faire une multiplication
```{r, eval = TRUE, solution = TRUE}
2*5
```
##### 


Bloc warning

```{block, box.type = "warning"}
Attention à ne pas utiliser **dplyr** !
```






